import { PlatformOption } from '../models/platform-options.model';

export const platformOptions: PlatformOption[] = [
  {
    bgColour: '#1A1A1A',
    label: 'GitHub',
    value: 'github',
    iconPath: '../../../assets/images/icon-github.svg',
    urlPattern: /^https?:\/\/(www\.)?github\.com(\/.*)?$/,
    placeholder: 'https://github.com/username/repository',
  },
  {
    bgColour: '#FFFFFF',
    label: 'Frontend Mentor',
    value: 'frontend_mentor',
    iconPath: '../../../assets/images/icon-frontend-mentor.svg',
    urlPattern: /^https?:\/\/(www\.)?frontendmentor\.io(\/.*)?$/,
    placeholder: 'https://www.frontendmentor.io/challenges',
  },
  {
    bgColour: '#43B7E9',
    label: 'Twitter',
    value: 'twitter',
    iconPath: '../../../assets/images/icon-twitter.svg',
    urlPattern: /^https?:\/\/(www\.)?twitter\.com(\/.*)?$/,
    placeholder: 'https://twitter.com/username',
  },
  {
    bgColour: '#2D68FF',
    label: 'LinkedIn',
    value: 'linkedin',
    iconPath: '../../../assets/images/icon-linkedin.svg',
    urlPattern: /^https?:\/\/(www\.)?linkedin\.com(\/.*)?$/,
    placeholder: 'https://www.linkedin.com/in/username',
  },
  {
    bgColour: '#EE3939',
    label: 'YouTube',
    value: 'youtube',
    iconPath: '../../../assets/images/icon-youtube.svg',
    urlPattern: /^https?:\/\/(www\.)?youtube\.com(\/.*)?$/,
    placeholder: 'https://www.youtube.com/channel/CHANNEL_ID',
  },
  {
    bgColour: '#2442AC',
    label: 'Facebook',
    value: 'facebook',
    iconPath: '../../../assets/images/icon-facebook.svg',
    urlPattern: /^https?:\/\/(www\.)?facebook\.com(\/.*)?$/,
    placeholder: 'https://www.facebook.com/username',
  },
  {
    bgColour: '#EE3FC8',
    label: 'Twitch',
    value: 'twitch',
    iconPath: '../../../assets/images/icon-twitch.svg',
    urlPattern: /^https?:\/\/(www\.)?twitch\.tv(\/.*)?$/,
    placeholder: 'https://www.twitch.tv/username',
  },
  {
    bgColour: '#333333',
    label: 'Dev.to',
    value: 'dev_to',
    iconPath: '../../../assets/images/icon-devto.svg',
    urlPattern: /^https?:\/\/(www\.)?dev\.to(\/.*)?$/,
    placeholder: 'https://dev.to/username',
  },
  {
    bgColour: '#8A1A50',
    label: 'Codewars',
    value: 'codewars',
    iconPath: '../../../assets/images/icon-codewars.svg',
    urlPattern: /^https?:\/\/(www\.)?codewars\.com(\/.*)?$/,
    placeholder: 'https://www.codewars.com/users/username',
  },
  {
    bgColour: '#1E1F26',
    label: 'Codepen',
    value: 'codepen',
    iconPath: '../../../assets/images/icon-codepen.svg',
    urlPattern: /^https?:\/\/(www\.)?codepen\.io(\/.*)?$/,
    placeholder: 'https://codepen.io/username',
  },
  {
    bgColour: '#302267',
    label: 'freeCodeCamp',
    value: 'freecodecamp',
    iconPath: '../../../assets/images/icon-freecodecamp.svg',
    urlPattern: /^https?:\/\/(www\.)?freecodecamp\.org(\/.*)?$/,
    placeholder: 'https://www.freecodecamp.org/username',
  },
  {
    bgColour: '#EB4925',
    label: 'GitLab',
    value: 'gitlab',
    iconPath: '../../../assets/images/icon-gitlab.svg',
    urlPattern: /^https?:\/\/(www\.)?gitlab\.com(\/.*)?$/,
    placeholder: 'https://gitlab.com/username',
  },
  {
    bgColour: '#0330D1',
    label: 'Hashnode',
    value: 'hashnode',
    iconPath: '../../../assets/images/icon-hashnode.svg',
    urlPattern: /^https?:\/\/(www\.)?hashnode\.com(\/.*)?$/,
    placeholder: 'https://hashnode.com/@username',
  },
  {
    bgColour: '#EC7100',
    label: 'Stack Overflow',
    value: 'stack_overflow',
    iconPath: '../../../assets/images/icon-stack-overflow.svg',
    urlPattern: /^https?:\/\/(www\.)?stackoverflow\.com(\/.*)?$/,
    placeholder: 'https://stackoverflow.com/users/userId/username',
  },
];
